### ISSUE TITLE
RepeatMasker_SVA_hg19.bed the same as RepeatMasker_Alu_hg19.bed in resource folder

### ISSUE THREAD

**Issue by ATPs** [clemgoub/reGenotypeTE#6]
Dear TypeTE authors.
Thank you for providing this tool to the scientific community.

We are using WES data. MELT works on WES data. We tested several other tools to call TE, and most of them do not work on WES data. We also tested TypeTE a lot, but haven't found the proper way of running it. But we would like to seek help from you.

We got the MELT output. To run TypeTE, what should we do first? do we need to filter "PASS" first, or use the raw output of MELT directly?

should we use "input_from_melt.sh" and "[input_from_melt_Del.sh](https://github.com/clemgoub/TypeTE/blob/master/input_from_melt_Del.sh)" first?

how to create [refinelib](https://github.com/clemgoub/TypeTE/blob/master/Ressources/refinelib) from L1 and SVA? based on the bed files and extract fasta file from the genome?

Also, the RepeatMasker_SVA_hg19.bed is the same as RepeatMasker_Alu_hg19.bed in resource folder. why is that?

Hope to get some advice from you.
Thank you and best wishes!
Xiaolong

**Comment by clemgoub** [comment]
Hello Xiaolong,

Thanks for reaching out. If you are interested in improving the MELT genotypes for REFERENCE TE (MELT Deletion), I recommend to use **TypeREF**, which has a better and more reliable framework.

You can find the TypeREF software and documentation here: https://github.com/clemgoub/typeref
And step-by-step tutorial, using MELT's output here: https://link.springer.com/protocol/10.1007/978-1-0716-2883-6_4

For your specific questions:
- Use the raw output of MELT
- TypeTE is design to only work on Alu (especially the non-reference mode)
- Thanks for reporting the error in the files in the Type**TE.** If believe that this is fixed in Type**REF**

If you are also interested in non-reference insertions, I would recommend, instead of TypeTE, to use either:
- [ERVcaller](https://github.com/xunchen85/ERVcaller)
- [xTEA](https://github.com/parklab/xTea/tree/master)
- [MEGAnE](https://github.com/shohei-kojima/MEGAnE) (though MELT seems better at non-reference; it can be a good comparison.)

Hope this helps! Let me know if you need further information!

Cheers,

Clément

**Comment by ATPs** [comment]
Thank you very much for clarifying this. We are interested in non-reference insertions.
We tested [xTEA](https://github.com/parklab/xTea/tree/master) and [MEGAnE](https://github.com/shohei-kojima/MEGAnE), and they seem not work on WES data.
We will test [ERVcaller](https://github.com/xunchen85/ERVcaller).

Best.

**Comment by ATPs** [comment]
We just tested ERVcaller. All genotype were "1/1". Note sure why. Quite different from MELT. We will still use MELT...
